# Generated by Django 3.2.5 on 2021-07-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_datecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(to='news.Category', verbose_name='Категория'),
        ),
    ]
